# Generated by Django 4.0.3 on 2022-03-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='myimage')),
                ('title', models.CharField(max_length=50, null=True)),
                ('discription', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Number',
            new_name='number',
        ),
    ]
