# Generated by Django 4.0.3 on 2022-03-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0002_blog_gallery_rename_number_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='discription',
            new_name='description',
        ),
    ]
