# Generated by Django 4.0.3 on 2022-03-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0003_rename_discription_blog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Gallery',
            new_name='gallery',
        ),
    ]
