# Generated by Django 4.0.3 on 2022-03-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0005_alter_gallery_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
