# Generated by Django 4.0.3 on 2022-03-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0006_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='myprofile')),
                ('name', models.CharField(max_length=50, null=True)),
                ('equcation', models.CharField(max_length=50, null=True)),
                ('sub_title', models.CharField(max_length=100, null=True)),
                ('facebooklinks', models.CharField(max_length=300, null=True)),
                ('instagramlinks', models.CharField(max_length=300, null=True)),
                ('linkedinlinks', models.CharField(max_length=300, null=True)),
                ('twitterlinks', models.CharField(max_length=300, null=True)),
                ('youtubelinks', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
