# Generated by Django 4.0.3 on 2022-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0007_key_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('discription', models.TextField(max_length=500, null=True)),
                ('email_id', models.EmailField(max_length=100, null=True)),
                ('Contact_details', models.IntegerField()),
                ('Address', models.TextField(max_length=200, null=True)),
                ('facebookicon', models.ImageField(null=True, upload_to='mysocialmediaicon')),
                ('instagramicon', models.ImageField(null=True, upload_to='mysocialmediaicon')),
                ('linkedinicon', models.ImageField(null=True, upload_to='mysocialmediaicon')),
                ('twittericon', models.ImageField(null=True, upload_to='mysocialmediaicon')),
            ],
        ),
    ]
