# Generated by Django 4.0.3 on 2022-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0011_contact_page_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicraft_About_Bamboo_itom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Bamboo_itom_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Handicraft_About_Flower_pot_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Flower_pot_products_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Handicraft_About_Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_furniture_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Handicraft_Decorative_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Decorative_products_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Handicraft_wooden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wooden_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Handicraft_Wooden_Temples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wooden_Temples_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact_page',
            name='map',
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='Contact_details',
            field=models.IntegerField(max_length=50),
        ),
    ]
