# Generated by Django 4.0.3 on 2022-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0012_handicraft_about_bamboo_itom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handicraft_decorative_products',
            old_name='Decorative_products_handicraft_image',
            new_name='decorative_handicraft_image',
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='Contact_details',
            field=models.IntegerField(),
        ),
    ]
