# Generated by Django 4.0.3 on 2022-03-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0014_homesliding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients')),
                ('name', models.CharField(max_length=50)),
                ('company_country', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Homesliding',
        ),
    ]
