# Generated by Django 4.0.3 on 2022-04-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0015_clients_delete_homesliding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certification')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
