# Generated by Django 4.0.3 on 2022-04-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0016_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.URLField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
