# Generated by Django 4.0.3 on 2022-04-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0017_location_delete_certification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
