# Generated by Django 4.0.3 on 2022-04-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0019_alter_contact_page_contact_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('sub_description', models.TextField(max_length=500)),
            ],
        ),
    ]
