# Generated by Django 4.0.3 on 2022-04-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0020_about_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_company',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about_company',
            name='sub_description',
            field=models.TextField(max_length=1000),
        ),
    ]
