# Generated by Django 4.0.3 on 2022-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0021_alter_about_company_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicraft_clay_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Flower_pot_products_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Handicraft_incense_sticks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wooden_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Handicraft_jute_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wooden_Temples_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Handicraft_wood_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Bamboo_itom_handicraft_image', models.ImageField(upload_to='handicraft')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('sub_title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='handicraft')),
                ('title_image1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='handicraft')),
                ('title_image2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='handicraft')),
                ('title_image3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='handicraft')),
                ('title_image4', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Handicraft_Wooden_Temples',
            new_name='Handicraft_bamboo_products',
        ),
        migrations.RenameModel(
            old_name='Handicraft_About_Bamboo_itom',
            new_name='Handicraft_Candles',
        ),
        migrations.DeleteModel(
            name='Handicraft_About_Flower_pot_products',
        ),
        migrations.DeleteModel(
            name='Handicraft_About_Furniture',
        ),
        migrations.DeleteModel(
            name='Handicraft_Decorative_products',
        ),
        migrations.DeleteModel(
            name='Handicraft_wooden',
        ),
        migrations.RemoveField(
            model_name='handicraft_bamboo_products',
            name='Wooden_Temples_handicraft_image',
        ),
        migrations.RemoveField(
            model_name='handicraft_candles',
            name='About_Bamboo_itom_handicraft_image',
        ),
        migrations.AddField(
            model_name='handicraft_bamboo_products',
            name='About_furniture_handicraft_image',
            field=models.ImageField(default=1, upload_to='handicraft'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handicraft_candles',
            name='decorative_handicraft_image',
            field=models.ImageField(default=2, upload_to='handicraft'),
            preserve_default=False,
        ),
    ]
