# Generated by Django 3.2.6 on 2022-04-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0023_bamboo_products_bamboo_products_photos_candles_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jute_products',
        ),
        migrations.DeleteModel(
            name='Jute_products_photos',
        ),
    ]
