# Generated by Django 3.2.6 on 2022-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0025_love_for_clients1_love_for_clients2_love_for_clients3_love_for_clients4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_person',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
