# Generated by Django 3.2.6 on 2022-04-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0026_alter_key_person_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamboo_products_photos',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='candles_photos',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='clay_products_photos',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='incense_photos',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wood_products_photos',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
